name: "Test"
on:
  pull_request:
  push:
  schedule:
    # every sunday morning
    - cron: "0 0 * * 0"
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-build ci.nix
      - run: mkdir artifacts
      - run: cp result/* artifacts/
      - run: find .
      - name: Upload lore
        uses: actions/upload-artifact@v2
        with:
          name: ubuntu-lore
          path: artifacts
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-build ci.nix
      - run: mkdir artifacts
      - run: cp result/* artifacts/
      - run: find .
      - name: Upload lore
        uses: actions/upload-artifact@v2
        with:
          name: macos-lore
          path: artifacts

  analyze:
    name: Analyze binlore
    needs: [ubuntu, macos]
    runs-on: ubuntu-latest
    steps:
      - name: Download lore
        uses: actions/download-artifact@v2
      - run: find .
      - run: sed -E 's^/nix/store/[a-z0-9]{32}-^ ^' ubuntu-lore/execers | sort -k2 > ubuntu
      - run: sed -E 's^/nix/store/[a-z0-9]{32}-^ ^' macos-lore/execers | sort -k2 > macos
      - run: diff -u macos ubuntu
