name: "Test"
on:
  pull_request:
  push:
  schedule:
    # every sunday morning
    - cron: "0 0 * * 0"
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-build ci.nix
      - run: mkdir artifacts
      - run: cp result/* artifacts/
      - name: Generate underlying YARA rule matches
        run: |
          nix-build matches.nix
          cat result > artifacts/matches
      - name: Upload lore
        uses: actions/upload-artifact@v2
        with:
          name: ubuntu-lore
          path: artifacts
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-build ci.nix
      - run: mkdir artifacts
      - run: cp result/* artifacts/
      - name: Generate underlying YARA rule matches
        run: |
          nix-build matches.nix
          cat result > artifacts/matches
      - name: Upload lore
        uses: actions/upload-artifact@v2
        with:
          name: macos-lore
          path: artifacts

  analyze:
    name: Analyze binlore
    needs: [ubuntu, macos]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download lore
        uses: actions/download-artifact@v2
      - name: De-hash execer paths
        run: |
          sed -E 's^/nix/store/[a-z0-9]{32}-^ ^' ubuntu-lore/execers > ubuntu
          sed -E 's^/nix/store/[a-z0-9]{32}-^ ^' macos-lore/execers > macos
      - name: Show raw YARA rule matches for ... on ubuntu
        run: cat ubuntu-lore/matches
      - name: Show raw YARA rule matches for ... on macos
        run: cat macos-lore/matches
      - name: Show full binlore on ubuntu
        run: cat ubuntu-lore/execers
      - name: Show full binlore on macos
        run: cat macos-lore/execers
      - name: Compare macos v. ubuntu
        run: ./compare_ci.py
